### PR TITLE
Completed back-end (for now)

### PR DESCRIPTION
**Pull request by santiago-a-serrano**

### CODE REVIEW

**Review by thienantran010 — COMMENTED** [review]
why is value=\"\" ? Is this a typo

**Review by thienantran010 — COMMENTED** [review]
to prevent the major cookie from being null we can force the user to select a major before the form is submitted

**Comment by santiago-a-serrano** [comment]
> Line 30 of GetMajorServelets.java: why is value=\"\" ? Is this a typo

It seems the drop-down must have values in all its options for it to work correctly (or at least to avoid weird behavior). At least that's what I understood from what Andrew told me. Since Line 30 is not a major, we can basically put any value there.

**Comment by santiago-a-serrano** [comment]
> to prevent the major cookie from being null we can force the user to select a major before the form is submitted

You're right

**Review by thienantran010 — COMMENTED** [review]
i think any function with await has to be async so loadItems is probably fine

**Review by thienantran010 — COMMENTED** [review]
this looks good. could you explain the getItemsArray function? I'm a little lost there because I'm not as familiar with datastore lol. What do you get when you run the query? And why did you use a stack? Is it not possible to put the items into responseArray from the list

**Comment by aaron-prindle-sps** [comment]
LGTM! Can you rebase the PR, currently there is a conflicting file given some of the other code changes that have gone it:

Conflicting files:
```
project/src/main/webapp/results.html
```

**Comment by santiago-a-serrano** [comment]
> this looks good. could you explain the getItemsArray function? I'm a little lost there because I'm not as familiar with datastore lol. What do you get when you run the query? And why did you use a stack? Is it not possible to put the items into responseArray from the list

We use a stack because we will be accessing each item once, so we can just access an item and then pop it. Just thought it was a little bit more efficient than using a list (but we can change it to a list if it's too confusing).

The code is a little confusing since the Datastore library uses some concepts and data structures that are not very intuitive at first.

I'll explain later with a short video.

**Pull request merged**
